In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load and Quick Quality Assessment of Data

In [31]:
df = pd.read_csv('data/bank-additional-full.csv', sep=';')

In [32]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 41188 entries, 0 to 41187
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             41188 non-null  int64
 1   job             41188 non-null  str
 2   marital         41188 non-null  str
 3   education       41188 non-null  str
 4   default         41188 non-null  str
 5   housing         41188 non-null  str
 6   loan            41188 non-null  str
 7   contact         41188 non-null  str
 8   month           41188 non-null  str
 9   day_of_week     41188 non-null  str
 10  duration        41188 non-null  int64
 11  campaign        41188 non-null  int64
 12  pdays           41188 non-null  int64
 13  previous        41188 non-null  int64
 14  poutcome        41188 non-null  str
 15  emp.var.rate    41188 non-null  float64
 16  cons.price.idx  41188 non-null  float64
 17  cons.conf.idx   41188 non-null  float64
 18  euribor3m       41188 non-null  float64
 19  nr.employed     41188 non-null  float64
 20  y               41188 non-null  str
dtypes: float64(5), int64(5), str(11)
memory usage: 6.6 MB

In [33]:
# Display summary statistics for each column
for col in df.columns:
    print(f"{col} " + "=" * 50)
    if df[col].dtype == 'str':
        print(df[col].value_counts())
    elif df[col].dtype in ['int64', 'float64']:
        print(df[col].describe())
        print("Missing values:", df[col].isnull().sum())
    print()

age ==================================================
count    41188.00000
mean        40.02406
std         10.42125
min         17.00000
25%         32.00000
50%         38.00000
75%         47.00000
max         98.00000
Name: age, dtype: float64
Missing values: 0

job ==================================================
job
admin.           10422
blue-collar       9254
technician        6743
services          3969
management        2924
retired           1720
entrepreneur      1456
self-employed     1421
housemaid         1060
unemployed        1014
student            875
unknown            330
Name: count, dtype: int64

marital ==================================================
marital
married     24928
single      11568
divorced     4612
unknown        80
Name: count, dtype: int64

education ==================================================
education
university.degree      12168
high.school             9515
basic.9y                6045
professional.course     5243
basic.4y                4176
basic.6y                2292
unknown                 1731
illiterate                18
Name: count, dtype: int64

default ==================================================
default
no         32588
unknown     8597
yes            3
Name: count, dtype: int64

housing ==================================================
housing
yes        21576
no         18622
unknown      990
Name: count, dtype: int64

loan ==================================================
loan
no         33950
yes         6248
unknown      990
Name: count, dtype: int64

contact ==================================================
contact
cellular     26144
telephone    15044
Name: count, dtype: int64

month ==================================================
month
may    13769
jul     7174
aug     6178
jun     5318
nov     4101
apr     2632
oct      718
sep      570
mar      546
dec      182
Name: count, dtype: int64

day_of_week ==================================================
day_of_week
thu    8623
mon    8514
wed    8134
tue    8090
fri    7827
Name: count, dtype: int64

duration ==================================================
count    41188.000000
mean       258.285010
std        259.279249
min          0.000000
25%        102.000000
50%        180.000000
75%        319.000000
max       4918.000000
Name: duration, dtype: float64
Missing values: 0

campaign ==================================================
count    41188.000000
mean         2.567593
std          2.770014
min          1.000000
25%          1.000000
50%          2.000000
75%          3.000000
max         56.000000
Name: campaign, dtype: float64
Missing values: 0

pdays ==================================================
count    41188.000000
mean       962.475454
std        186.910907
min          0.000000
25%        999.000000
50%        999.000000
75%        999.000000
max        999.000000
Name: pdays, dtype: float64
Missing values: 0

previous ==================================================
count    41188.000000
mean         0.172963
std          0.494901
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max          7.000000
Name: previous, dtype: float64
Missing values: 0

poutcome ==================================================
poutcome
nonexistent    35563
failure         4252
success         1373
Name: count, dtype: int64

emp.var.rate ==================================================
count    41188.000000
mean         0.081886
std          1.570960
min         -3.400000
25%         -1.800000
50%          1.100000
75%          1.400000
max          1.400000
Name: emp.var.rate, dtype: float64
Missing values: 0

cons.price.idx ==================================================
count    41188.000000
mean        93.575664
std          0.578840
min         92.201000
25%         93.075000
50%         93.749000
75%         93.994000
max         94.767000
Name: cons.price.idx, dtype: float64
Missing values: 0

cons.conf.idx ==================================================
count    41188.000000
mean       -40.502600
std          4.628198
min        -50.800000
25%        -42.700000
50%        -41.800000
75%        -36.400000
max        -26.900000
Name: cons.conf.idx, dtype: float64
Missing values: 0

euribor3m ==================================================
count    41188.000000
mean         3.621291
std          1.734447
min          0.634000
25%          1.344000
50%          4.857000
75%          4.961000
max          5.045000
Name: euribor3m, dtype: float64
Missing values: 0

nr.employed ==================================================
count    41188.000000
mean      5167.035911
std         72.251528
min       4963.600000
25%       5099.100000
50%       5191.000000
75%       5228.100000
max       5228.100000
Name: nr.employed, dtype: float64
Missing values: 0

y ==================================================
y
no     36548
yes     4640
Name: count, dtype: int64

In [34]:
# missing values
missing_values = (df == 'unknown').sum()
percent_missing = ((missing_values / len(df)) * 100).round(2)
missing_df = pd.DataFrame({'Missing Values': missing_values, 'Percent Missing': percent_missing})
print(missing_df[missing_df['Missing Values'] > 0])

rows_with_missing = ((df == 'unknown') | df.isnull()).any(axis=1).sum()
percent_missing = (rows_with_missing / len(df)) * 100
print(f"\nNumber of rows with missing values: {rows_with_missing} ({percent_missing:.2f}%)")

           Missing Values  Percent Missing
job                   330             0.80
marital                80             0.19
education            1731             4.20
default              8597            20.87
housing               990             2.40
loan                  990             2.40

Number of rows with missing values: 10700 (25.98%)

In [35]:
df['y'].value_counts() / len(df) * 100

y
no     88.734583
yes    11.265417
Name: count, dtype: float64

## Handling Missing Values

**SUMMARY**
- test for MCAR, MNAR
- multinomial logistic regression for nominal features
- KNN imputation for ordinal features

# Preprocessing

**Imputation Summary**
- treat `unknown` (string) as missing value
- treat missing values for `default` as a category
- test for MCAR, MNAR
- multinomial logistic regression for nominal features
- KNN imputation for ordinal features

**Transformation Summary**
- transform `y` to boolean
- drop `duration`, `pdays` column
- one-hot encode `job`, `marital`, `education`, `contact`, `month`, and `day_of_week`
- ordinal encode `education`
- multicollinearity check
  - drop `poutcome_nonexistent` due to high correlation with `previous`
  - perform PCA for macroeconomic indicators (`cons.price.id`, `euribor3m`, `nr.employed`, `euribor3m`)

## Test for MCAR, MNAR

In [36]:
from lib import *

In [37]:
mcar_test_results = tp_test_mcar(df)

In [38]:
missing_cols = ["job", "marital", "education", "default", "housing", "loan"]
significants = mcar_test_results[
    (mcar_test_results['missing_column'] != 'default')          # treat missing default as a separate category
    & (mcar_test_results['p_value'] < 0.05)                     # significant association with tested column
    & (~mcar_test_results['tested_column'].isin(missing_cols))  # exclude columns with missing values as tested columns
].sort_values('missing_column')
print(significants['missing_column'].unique())
significants
# From this, we can see that all missing columns are not MCAR

<StringArray>
['education', 'housing', 'job', 'loan', 'marital']
Length: 5, dtype: str

    missing_column   tested_column       p_value
29       education               y  1.629895e-05
89       education     nr.employed  1.048714e-03
88       education       euribor3m  4.915301e-03
87       education   cons.conf.idx  9.867530e-06
25       education         contact  3.416578e-05
26       education           month  6.544704e-19
27       education     day_of_week  8.552996e-04
28       education        poutcome  7.100547e-04
80       education             age  9.500015e-40
86       education  cons.price.idx  2.793088e-11
84       education        previous  7.188848e-03
83       education           pdays  9.616965e-06
45         housing         contact  7.825563e-06
46         housing           month  1.649939e-04
106        housing  cons.price.idx  1.006719e-04
5              job         contact  2.570434e-06
68             job       euribor3m  3.493543e-03
63             job           pdays  1.821379e-02
66             job  cons.price.idx  7.663820e-08
65             job    emp.var.rate  3.565629e-03
60             job             age  7.564658e-21
8              job        poutcome  1.041906e-03
7              job     day_of_week  8.078340e-03
6              job           month  9.176034e-07
67             job   cons.conf.idx  7.136459e-12
56            loan           month  1.649939e-04
55            loan         contact  7.825563e-06
116           loan  cons.price.idx  1.006719e-04
74         marital        previous  2.042964e-02

## Imputation

In [39]:
from lib import *
from sklearn.model_selection import train_test_split

# split into train/test before imputation to avoid data leakage
df_train, df_test = train_test_split(df, test_size=0.2, random_state=42)

In [46]:
# take ~4 mins
logreg_opts = {
    'solver': 'newton-cg',
    'max_iter': 1000,
}
multi_imputer = TPMultinomialImputer(logreg_opts=logreg_opts)
multi_imputer.fit(df_train)

In [47]:
df_train_multi_imputed = multi_imputer.transform(df_train, verbose=True)

Imputation summary for 'job':
               Before  Percent Before   After  Imputed  Percent Imputed
job
admin.           8328           25.27  8420.0     92.0             0.35
blue-collar      7439           22.58  7559.0    120.0             0.46
technician       5352           16.24  5365.0     13.0             0.05
services         3212            9.75  3212.0      0.0             0.00
management       2310            7.01  2310.0      0.0             0.00
retired          1363            4.14  1395.0     32.0             0.12
self-employed    1153            3.50  1153.0      0.0             0.00
entrepreneur     1145            3.47  1145.0      0.0             0.00
housemaid         867            2.63   867.0      0.0             0.00
unemployed        798            2.42   798.0      0.0             0.00
student           721            2.19   726.0      5.0             0.02
unknown           262            0.80     NaN      NaN              NaN

Imputation summary for 'marital':
          Before  Percent Before    After  Imputed  Percent Imputed
marital
married    19823           60.16  19872.0     49.0              0.8
single      9333           28.32   9345.0     12.0              0.2
divorced    3733           11.33   3733.0      0.0              0.0
unknown       61            0.19      NaN      NaN              NaN

Imputation summary for 'housing':
         Before  Percent Before    After  Imputed  Percent Imputed
housing
yes       17257           52.37  17774.0    517.0             0.64
no        14882           45.17  15176.0    294.0             0.36
unknown     811            2.46      NaN      NaN              NaN

Imputation summary for 'loan':
         Before  Percent Before    After  Imputed  Percent Imputed
loan
no        27135           82.35  27946.0    811.0              1.0
yes        5004           15.19   5004.0      0.0              0.0
unknown     811            2.46      NaN      NaN              NaN

In [48]:
df_test_multi_imputed = multi_imputer.transform(df_test, verbose=True)

Imputation summary for 'job':
               Before  Percent Before   After  Imputed  Percent Imputed
job
admin.           2094           25.42  2116.0     22.0             0.32
blue-collar      1815           22.03  1850.0     35.0             0.51
technician       1391           16.89  1393.0      2.0             0.03
services          757            9.19   757.0      0.0             0.00
management        614            7.45   614.0      0.0             0.00
retired           357            4.33   364.0      7.0             0.10
entrepreneur      311            3.78   311.0      0.0             0.00
self-employed     268            3.25   268.0      0.0             0.00
unemployed        216            2.62   216.0      0.0             0.00
housemaid         193            2.34   193.0      0.0             0.00
student           154            1.87   156.0      2.0             0.03
unknown            68            0.83     NaN      NaN              NaN

Imputation summary for 'marital':
          Before  Percent Before   After  Imputed  Percent Imputed
marital
married     5105           61.97  5117.0     12.0             0.63
single      2235           27.13  2242.0      7.0             0.37
divorced     879           10.67   879.0      0.0             0.00
unknown       19            0.23     NaN      NaN              NaN

Imputation summary for 'housing':
         Before  Percent Before   After  Imputed  Percent Imputed
housing
yes        4319           52.43  4423.0    104.0             0.58
no         3740           45.40  3815.0     75.0             0.42
unknown     179            2.17     NaN      NaN              NaN

Imputation summary for 'loan':
         Before  Percent Before   After  Imputed  Percent Imputed
loan
no         6815           82.73  6994.0    179.0              1.0
yes        1244           15.10  1244.0      0.0              0.0
unknown     179            2.17     NaN      NaN              NaN

In [49]:
knn_imputer = TPKNNImputer()
knn_imputer.fit(df_train)

In [ ]:
df_train_knn_imputed = knn_imputer.transform(df_train_multi_imputed, verbose=True)

In [ ]:
df_test_knn_imputed = knn_imputer.transform(df_test_multi_imputed, verbose=True)

## Transformations

In [52]:
df_train_transformed = tp_simple_transform(df_train_knn_imputed)
df_test_transformed = tp_simple_transform(df_test_knn_imputed)

In [53]:
df_train_encoded = tp_encode(df_train_transformed)
df_test_encoded = tp_encode(df_test_transformed)

In [54]:
# checkpoint
df_train_encoded.to_csv('data/df_train_encoded.csv', index=False)
df_test_encoded.to_csv('data/df_test_encoded.csv', index=False)

## Handle Multicollinearity

In [ ]:
# multicollinearity check
correlation_matrix = df_train_encoded.corr()
plt.figure(figsize=(12, 10))
sns.heatmap(correlation_matrix, annot=False, cmap='coolwarm', linewidths=0.5)
plt.title('Correlation Matrix')
plt.show()

In [56]:
"""
From this we can see that 
- 4 macroeconomic indicators are highly correlated with each other. ('cons.price.id', 'euribor3m', 'nr.employed', 'euribor3m')
- 'marital_single' and 'marital_married' are highly correlated. Will leave as is.
- 'poutcome_nonexistent' and 'previous' are highly correlated. Will drop 'poutcome_nonexistent'.
"""

# check for high correlation (> 0.7)
high_correlations = []
for i in range(len(correlation_matrix.columns)):
    for j in range(i):
        if abs(correlation_matrix.iloc[i, j]) > 0.7: # type: ignore
            high_correlations.append((
                correlation_matrix.columns[i], 
                correlation_matrix.columns[j], 
                correlation_matrix.iloc[i, j])
            )

df_high_corr = pd.DataFrame(high_correlations, columns=['col1', 'col2', 'correlation'])
df_high_corr

                   col1                  col2  correlation
0        cons.price.idx          emp.var.rate     0.773785
1             euribor3m          emp.var.rate     0.972084
2           nr.employed          emp.var.rate     0.906548
3           nr.employed             euribor3m     0.945144
4        marital_single       marital_married    -0.775600
5  poutcome_nonexistent              previous    -0.880837
6      poutcome_success  previously_contacted     0.950187

In [ ]:
df_train_encoded.drop(columns=['previously_contacted'], inplace=True)
df_test_encoded.drop(columns=['previously_contacted'], inplace=True)